### ISSUE TITLE
Flaky test: `TestHttpProbe/returns_the_status_code_if_the_request_is_successful`

### ISSUE THREAD

**Issue by jesusprubio** [jesusprubio/up#52]
Occurrences:
- https://github.com/jesusprubio/up/actions/runs/9686542637/job/26729185707
- https://github.com/jesusprubio/up/actions/runs/9686388900/job/26728671722

**Comment by abdoroot** [comment]
Hi, please check the following pull request:
https://github.com/jesusprubio/up/pull/55
