### ISSUE TITLE
Add binary releases

### ISSUE THREAD

**Issue by Allaman** [jesusprubio/up#73]
It would be very convenient. And I could add it to my tool [werkzeugkasten](https://github.com/Allaman/werkzeugkasten) :)

[goreleaser](https://github.com/goreleaser/goreleaser) does a fantastic job handling this. Cp. my [config](https://github.com/Allaman/werkzeugkasten/blob/main/.goreleaser.yml) (which is called via Github Action)

**Comment by jesusprubio** [comment]
Done here: https://github.com/jesusprubio/up/pull/32
And here: https://github.com/jesusprubio/up/issues/64

Will publish a new release once we merge a couple of pending PRs.

Thank you.
